# Set by github - do not change.
safe: true
lsi: false
highlighter: rouge

exclude:
- bower.json
- bower_components
- Gemfile
- Gemfile.lock

title: xenia
description: >
  xenia is a BSD licensed open source research project for emulating Xbox 360
  games on modern PCs.
baseurl:
url: "http://xenia.jp"
twitter_username: xeniaproject
github_username:  xenia-project

markdown: kramdown

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

navigation:
  - pages:
    - title: Home
      path: index.html
    - path: about.md
    - path: faq.md
    - path: download.md
    - path: roadmap.md
    - path: compatibility.html
    - path: gallery.html
  - title: Community
    pages:
    - title: /r/xenia
      url: https://www.reddit.com/r/xenia
      icon: forum
    - title: YouTube
      url: https://www.youtube.com/channel/UC6bJhkUUHE18HVG2mpbygSQ
      icon: videocam
    - title: "#xenia @ freenode"
      url: http://webchat.freenode.net/?channels=%23xenia
      icon: people
  - title: Development
    pages:
    - path: development/quickstart.md
    - path: development/debugging.md
    - title: Source Code
      url: https://github.com/benvanik/xenia
      icon: code
    - title: Issues
      url: https://github.com/benvanik/xenia/issues
      icon: bug_report
    - title: Buildbot
      url: http://build.xenia.jp/waterfall
      icon: settings_system_daydream
    - path: development/irc.md
